### ISSUE TITLE
Collision detection system

### ISSUE THREAD

**Issue by Tosiekdev** [AGH-Code-Industry/archimedes#61]
## Introduction
Collision detection can be said to be a system, which is definitely an obligatory part of every game engine. It is part of almost every interaction between entities acting in a game. It allows for implementing physics systems, as it can not only provide a way of testing whether two convex shapes interact, but also it gives a user the possibility of getting many important pieces of information like a point of collision and normal (perpendicular) vector.

## Implementation plan

- [ ] Create Colliders' classes #62 ,
- [ ] Create collision detection #63 ,
- [ ] Provide a way of giving information about a distance, collision point, and normal vector between any two convex colliders #64 ,
- [ ] Encapsulate it all in one system #65 

WE WILL PROVIDE FURTHER INFORMATION IN NOT DISTANT FUTURE in [this User Friendly format](https://www.youtube.com/watch?v=dQw4w9WgXcQ)
