### ISSUE TITLE
Create resource managment.

### ISSUE THREAD

**Issue by Challmymind** [AGH-Code-Industry/archimedes#66]
#49 Epic
# Introduction
Resource manager is vital part of any working game engine. It should provide managable abstraction for handling files inside any game project.
## What should provide such system ?
* Way of loading a asset from filesystem to the unified format for ex. any 3D object should be loaded as 3DModel and any audio file as
AudioObject.
* Loading and unloding of this objects from memory.
* Lazy loading so a model should not load until object is used in game or told explicity.
* Way of restricting assets from using whole momory. (to be considered)

# API
*Not final but planned version of API*
In the future there will be attempt to provide flexible loaders so user can add usability to the engine but now we should provide stable loaders for most crucial file extensions like obj to 3DModel.
``` cpp
3DModel asset = arch::load_asset<3DModel>("file.obj"); // Asset registered, here will be thrown error file hasn't been present.
// This asset isn't drawn by opengl but it's relative 0,0 coordinates are aligned with scene 0,0 coordinates.
// Asset still isn't present in memory, it's just registered.

asset.move(10,10,10); // Asset not loaded but added translation to it's origin.
asset.rotate(10,0,0); // Asset not loaded but added translation to it's origin.

asset.force_load(); // Asset present in memory, loaded explicitly but not drawn (if allocation cannot be performed throws error).
asset.force_unload(); // Asset no longer in memory but move and rotate methods hasn't been reversed.

Renderer3D renderer;
renderer.submit(asset); // Asset loaded implictly (lazy loading).
renderer.render(); Asset loaded on screen roated by (10,0,0) and with moved origin to (10,10,10).
// After end of the asset lifetime asset will be unloaded from memory if needed.
```

Example shows basic functions of ```3DModel``` and how user can force loding and unloding (usefull for loading screens) or leave some 
objects to be loaded by engine itself.

# Roadmap
*Worth noting that this might change in course of the time.*
- [ ] Create hardcoded support for loding .obj files.
- [ ] Extend for formats like .3ds, .blends, .fbx.
- [ ] Create support for AudioObject. (to be planned)
- [ ] Allow users to define their own loaders so they can extend capabilities of engine (if possible)

## Planned to be done by:
First bullet point of the list is planned to be done in __4 weeks__ at longest.
Assimp provides all utilities to load .obj file, what needs to be done is designing and implementing encapsulation abstractions like 3DModel. The idea is that after 4 weeks should be done first point and second with multiple file types supported.
Currently no function from this API will support threads so be careful.

**Comment by Challmymind** [comment]
Old issue #17 has been closed to be not misleading with this new version.
